# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

m1 = Message.create(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut convallis nibh nec dui molestie, posuere semper nisi laoreet. Aenean quis neque laoreet, volutpat arcu vitae, scelerisque purus. Nunc feugiat posuere pretium. Pellentesque sit amet turpis mi. Morbi placerat dolor at vulputate luctus. Suspendisse eros eros, maximus at vestibulum non, tincidunt ut sapien. Mauris vestibulum nisi velit, aliquet consequat magna ultricies ultricies. Nunc mattis diam justo, in vestibulum mi porta sed. Sed pharetra porta sem nec pulvinar. Maecenas efficitur sagittis quam, ut suscipit elit dignissim sit amet. Suspendisse dapibus, velit vitae pretium egestas, lacus erat egestas ante, sed finibus neque odio ut massa. Morbi consequat quam quis tristique dictum. Integer vel justo vehicula dolor rhoncus lacinia in ultricies libero. Donec augue nibh, tristique sit amet iaculis a, posuere non leo. Cras vestibulum erat nec rutrum egestas. Aenean tortor elit, tempus at neque vitae, placerat dignissim erat. ")

m2 = Message.create(content: "Praesent vulputate sollicitudin mollis. Nunc sit amet est quis nibh placerat dignissim mattis sit amet dui. Morbi odio est, laoreet a urna eu, euismod pretium diam. Duis maximus, quam eu volutpat volutpat, erat libero interdum urna, nec elementum nibh nisl eu lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer viverra erat eu dignissim pellentesque. Maecenas in luctus enim. Donec blandit vehicula nulla at vehicula. Cras tellus erat, tempor eu tempor vel, eleifend in ante. Vestibulum placerat ante consectetur, aliquam urna vel, lobortis leo. Morbi ut erat euismod, iaculis eros in, aliquam libero. Quisque ultricies felis sed elit eleifend, eu convallis mi porta. Donec ut dolor velit. ")

m3 = Message.create(content: "Nullam a tortor efficitur, feugiat quam vitae, efficitur velit. Nam nulla lacus, sollicitudin efficitur vulputate eu, facilisis ac mi. Praesent vel magna eu lacus volutpat pulvinar. Proin luctus massa sit amet dolor ultrices luctus. Curabitur et turpis diam. Vestibulum gravida scelerisque leo, non luctus metus sodales non. Donec laoreet nisl id mi feugiat, vel tristique quam malesuada. Ut ex urna, tincidunt eget accumsan maximus, blandit vel nulla. Duis euismod eu nisi a luctus. ")
